import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { Jost, Oswald } from "next/font/google";
import ScrollToTop from "@components/ScrollToTop";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

const oswald = Oswald({
	variable: "--oswald",
	display: "swap",
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin", "vietnamese"],
});

const jost = Jost({
	subsets: ["latin"],
	variable: "--font-jost",
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "La Photo | Search Images API",
	description: "Generated by create next app",
};

export const revalidate = 3600;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link rel="apple-touch-icon" sizes="180x180" href="./apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="./favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="./favicon-16x16.png" />
				<link rel="manifest" href="/site.webmanifest" />
			</head>
			<body className={`${jost.className} ${oswald.className} antialiased`}>
				<Header />
				<div className="main min-h-[calc(100vh-80px)]">{children}</div>
				<ScrollToTop />
				<Footer />
			</body>
		</html>
	);
}
